added _persistEEPROM
krzychb/EspSaveCrash pull request #15
Opened 2022-01-17 03:28 UTC by bwjohns4

This allows users who are already using EEPROM to continue in an intuitive way and not have this library close the EEPROM by calling EEPROM.end() within the library. Now in the constructor if you set persistent = true then this library will commit() instead of .end().

2022-01-22 06:02 UTC, krzychb requested changes
Thank you for noticing #14 and preparing the updates @bwjohns4!
Could you please add [braces](https://stackoverflow.com/questions/12193170/whats-the-purpose-of-using-braces-i-e-for-a-single-line-if-or-loop) to the newly added if statements?

2022-01-22 06:04 UTC, krzychb requested changes

2022-01-22 06:04 UTC, krzychb commented on src/EspSaveCrash.cpp
> +  else EEPROM.commit();
Braces are missing.

2022-01-22 06:04 UTC, krzychb commented on src/EspSaveCrash.cpp
> +  else EEPROM.commit();
Braces are missing.

2022-01-22 06:12 UTC, krzychb commented on src/EspSaveCrash.h
>  };
Please squash commit after doing the updates.

2022-01-22 06:17 UTC, krzychb commented
@bwjohns4,

Thank you for taking the time to submit this PR.

The updates look very good!

Please consider updating [Library Configuration](https://github.com/krzychb/EspSaveCrash/blob/master/examples.md#library-configuration) section of the documentation with the newly added parameter.  I think users may miss the extra functionality you provided if it is not documented.

2022-01-22 15:34 UTC, bwjohns4 commented
I added the braces and updated the ReadMe. Please let me know if anything else is needed. I'm not sure how to squash the commits since I've already pushed to the remote. Are you able to do that when you merge this in?

2022-01-23 03:48 UTC, merged

2022-01-23 03:49 UTC, krzychb commented
@bwjohns4, thank you for the quick updates!